global:
  # 全局SMTP配置
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

# 模版文件路径（容器里的路径，通过secret挂载）
templates: 
- '/etc/alertmanager/template/*.tmpl'

# 顶层路由
route:
  # 分组
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 

  # 报警接收器
  receiver: email

  routes:
  - match_re:
      service: ^(foo1|foo2|baz)$
    receiver: wechat
    routes:
    - match:
        severity: critical
      receiver: wechat
  - match:
      service: files
    receiver: email

    routes:
    - match:
        severity: critical
      receiver: email


# 报警接收器
receivers:
# 邮件
- name: 'email'
  email_configs:
  - to: 'team-X+alerts@example.org'

# 微信
- name: 'wechat'
  wechat_configs:
  - send_resolved: true
    api_secret: 'xxxx'
    corp_id: 'xxxxx'
    agent_id: 00001
    to_party: xxx
    to_tag: xxx

